# -*- coding: utf-8 -*-
"""Practice#1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUfxHvny5a34N7peLgEhWbP2pAC4AEJE
"""


# Baseball game_2nd trial

import random

list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
fix = []

fix = random.sample(list, 3)


print(fix)

trial = 0

while True:
  trial = trial + 1
  guess = input("Guess three numbers: ")
  guessS = guess.split(" ")
  s = 0
  b = 0

  for i in range(0, 3):
    if fix[i] == int(guessS[i]):
      s = s + 1

  for i in range(0, 3):
    for k in range(0, 3):
      if fix[i] == int(guessS[k]) and i != k:
       b = b + 1
  print("%dS %dB" %(s,b))
  if s == 3:
    break

print("Congratulations!")
print("You won with %d trials" %trial)