# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17EBHDhr7zaJ3yX6px3AEL1RxJvVLHh5o
"""

# Cryptography

n = int(input("Shift? "))
pt = input("Input a sentence: ")
ct = ''

for i in pt:
  c = i
  if i.isalpha() == True:
    an = ord(i) + n
    c = chr(an)
  
  ct = ct + c

print(ct)