# -*- coding: utf-8 -*-
"""Homerun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4ROLrNDBXMjeLp8vUGjp_38l0L1zjD1
"""

import math
u = int(input("Initial velocitity of the ball (km/h)? ")) * (10 / 36)
angle = int(input("Launch angle? "))
sin = math.sin(math.radians(angle))
cos = math.cos(math.radians(angle))

a = 9.8
t = ((u * sin) / a) * 2
dis = u * cos * t

print("The flying distance is %s meters." %dis)
if dis >= 120:
  print("It will be a homerun.")
else:
  print("It will not be a houmerun.")